train: /app/container/dataset/contour-mask-det/images/train
val: /app/container/dataset/contour-mask-det/images/val
test: /app/container/dataset/contour-mask-det/images/test
nc: 1
names: ['obstacle']
